version: '3'

services:
  pokemon-showdown:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/PokeLLMon
    tty: true
    env_file:
      - .env
    
    # command: npm start